// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtpvelnfIQ2cbCw9esKfJEGXsA768ZCJg',
    appId: '1:73398394844:web:cce2647eb423522f62b919',
    messagingSenderId: '73398394844',
    projectId: 'food-ordring-app-781fa',
    authDomain: 'food-ordring-app-781fa.firebaseapp.com',
    storageBucket: 'food-ordring-app-781fa.appspot.com',
    measurementId: 'G-9D80YC44S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa3oQWlKlx0M6u7Y6pxI0rHIQjuRDfE2U',
    appId: '1:73398394844:android:50c1a6645ddbcba962b919',
    messagingSenderId: '73398394844',
    projectId: 'food-ordring-app-781fa',
    storageBucket: 'food-ordring-app-781fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATCEK7ij8KyY2ME7hu8C9jZWtILDloZ_o',
    appId: '1:73398394844:ios:f251397f76865b0f62b919',
    messagingSenderId: '73398394844',
    projectId: 'food-ordring-app-781fa',
    storageBucket: 'food-ordring-app-781fa.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATCEK7ij8KyY2ME7hu8C9jZWtILDloZ_o',
    appId: '1:73398394844:ios:f251397f76865b0f62b919',
    messagingSenderId: '73398394844',
    projectId: 'food-ordring-app-781fa',
    storageBucket: 'food-ordring-app-781fa.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtpvelnfIQ2cbCw9esKfJEGXsA768ZCJg',
    appId: '1:73398394844:web:28048453213b8d3362b919',
    messagingSenderId: '73398394844',
    projectId: 'food-ordring-app-781fa',
    authDomain: 'food-ordring-app-781fa.firebaseapp.com',
    storageBucket: 'food-ordring-app-781fa.appspot.com',
    measurementId: 'G-HDRTJPKQJ6',
  );
}
